services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
