services:
  backend:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev --host"
    depends_on:
      - mongo

  mongo:
    image: mongo:noble
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo express allows us to inspect the contents of the db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
    name: mongo_data
