name: Check formatting with prettier

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        folder: 
          - "monolithic"
          - "micro-services/gateway-microservice"

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - run: npm install
      working-directory: ${{ matrix.folder }}

    - run: npm run format:check
      working-directory: ${{ matrix.folder }}
