name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        folder: ["monolithic"]

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '8.0'

    - run: npm install
      working-directory: ${{ matrix.folder }}

    - run: npm run test
      working-directory: ${{ matrix.folder }}
